---
title: "About"
subtitle: "a bit more about Mainak Bardhan and his journey"
title-block-banner: true
---

Dr. Mainak Bardhan is a physician–scientist with advanced training in **Genetics, Genomics, Pathology, and Epidemiology**, specializing in **neurological disorders, neuromuscular diseases,oncology, rare disorders, and infectious diseases**. His work is strongly grounded in **public health**, driven by a deep commitment to translating biomedical research into meaningful health outcomes.

He is currently pursuing his PhD in [Human Genetics and Genomics](https://med.miami.edu/graduate-studies/doctoral-programs/human-genetics-and-genomics) at the [The John P. Hussman Institute for Human Genomics (HIHG)](https://med.miami.edu/centers-and-institutes/hihg), [University of Miami Miller School of Medicine](https://welcome.miami.edu/), where he trains under the joint mentorship of [Prof. Danny Reinberg, PhD](https://www.hhmi.org/scientists/danny-reinberg), and [Prof. Ramin Shiekhattar, PhD](https://med.miami.edu/faculty/ramin-shiekhattar-phd)—two internationally recognized leaders in chromatin biology, epigenetics, and gene regulation.

---

## Early Research Foundations

Dr. Bardhan’s journey in clinical research began early during his medical degree training [MBBS](https://www.coursera.org/articles/mbbs-degree) at [Pandit. Jawahar Lal Nehru Memorial Medical College](https://ptjnmcraipur.in/) through the [**Indian Council of Medical Research (ICMR) Short Term Studentship (STS)** ](https://www.icmr.gov.in/short-term-studentship-sts)program. His initial work focused on **Sickle Cell Anemia** at the [Department of Biochemistry](https://ptjnmcraipur.in/Biochemistry.htm) and the [Sickle Cell Institute in Chhattisgarh](https://www.scic.cg.nic.in/), laying a strong foundation in disease-oriented research.

Throughout medical school, he actively pursued diverse research experiences, serving as a **Medical Student Research Trainee** at the [**CSIR–Centre for Cellular and Molecular Biology (CCMB), Hyderabad**](https://www.ccmb.res.in/) and **CSIR–Institute of Genomics and Integrative Biology (IGIB), New Delhi**, where he also worked as a **Visiting Medical Student**. These experiences broadened his exposure to molecular biology, genomics, and translational research.

---

## International Research Experience

In the penultimate year of his medical education, Dr. Bardhan presented his research at  25th [International Student Congress Of (bio)Medical Sciences(ISCOMS)](https://iscoms.com/) organised by the [**University of Groningen, Netherlands**](https://www.umcg.nl/), marking his early engagement with international scientific collaboration.

During his final year of medical school, he was selected as the **only medical student from India** to participate in the highly competitive [**Amgen Scholars Program**](https://amgenscholars.com/). Under technical mentorship from **Harvard University**, he conducted research at [**Tsinghua University’s School of Pharmaceutical Sciences (SPS)**](https://tsinghuaamgenscholars.com/2.html) in Beijing, consistently ranked among the world’s leading universities.

His research on **Solute Carrier Transporters (SLCs)** in the lab of [Prof. Ligong Chen](https://www.sps.tsinghua.edu.cn/info/1011/1395.htm) was showcased at the [**2019 Amgen Asia Scholars Symposium**](https://amgenscholars.com/2019-amgen-scholars-asia-symposium/) held at the **National University of Singapore (NUS)**, highlighting his contributions to molecular and pharmaceutical sciences.

---

## Neurogenetics & National Research Initiatives

Following completion of his medical degree, Dr. Bardhan joined [Prof.dr.Atchayaram Nalini,MD,PhD,MBA](https://indianscientist.in/nalini-atchayaram-neuroscience-best-research-award-3174/) at  [**National Institute of Mental Health and Neurosciences (NIMHANS)**](https://www.nimhans.ac.in/) in Bengaluru, India, as a **Senior Research Fellow** in the [Department of Neurology](https://www.nimhans.ac.in/departments/neurology). His work there focused on understanding the *clinical, epidemiological, genetics of various neuromuscular disorders* working in close collaboration with national and international clinicians and scientists.

At NIMHANS, he played a key role in spearheading the development of the [**National Registry for Rare and Other Inherited Disorders (NRROID)**](https://sansad.in/getFile/loksabhaquestions/annex/183/AU1843_hDSnsy.pdf?source=pqals)—a large, multicentric initiative led by the [**Indian Council of Medical Research (ICMR)**](https://www.icmr.gov.in/). This project represents a major national effort to advance rare disease research, diagnosis, and policy planning in India. 

---

## As Physician scientist

Dr. Bardhan got appointed by The Indian Council of Medical Research (ICMR), New Delhi, which is the apex body in India for the formulation, coordination and promotion of biomedical research, as a Physician Scientist and joined [ICMR-National Institute for Research in Bacterial Infections](https://niced.org.in/scientists/NICEDScientists/MainakBardhan.htm) 
There he continued his work at the intersection of **clinical research, genetics, and genomics**, with active involvement in **bacterial genetics and genomics**. His research there focused on Molecular pathogenesis,Antimicrobial resistance,Bacterial strain evolution,Genomic disease surveillance of various enteric pathogens

Through this work, he aims to strengthen **evidence-based public health strategies**, inform policy decisions, and contribute to improved community health and disease prevention.

---

## Research Philosophy

At the core of Dr. Bardhan’s work is a belief that **rigorous science, when integrated with clinical insight and public health awareness, can transform patient care and population health**. His research is guided by curiosity, collaboration, and a commitment to global health equity.



